### ISSUE TITLE
Generate SRTP and SRTCP keys

### ISSUE THREAD

**Issue by amrithathorath** [cisco/libsrtp#454] opened 2019-06-27 20:46 UTC
Hi,

I'm writing some code to generate SRTP and SRTCP keys using lib SRTP.
The input file from NIST looks like this (just 1 instance): 

```
[AES-128]

COUNT = 0
k_master = c4809f6d369888728e26adb532129890
master_salt = 0e23006c6c044f5662400e9d1bd6
kdr = 000000000000
index = 487165649cca
index (SRTCP) = 56f3f197
```
The outputs expected are 6 keys, shown below:

```
[AES-128]

COUNT = 0
k_master = c4809f6d369888728e26adb532129890
master_salt = 0e23006c6c044f5662400e9d1bd6
kdr = 000000000000
index = 487165649cca
index (SRTCP) = 56f3f197
SRTP k_e = dc382192ab65108a86b259b61b3af46f     // SRTP encryption key (output)
SRTP k_a = b83937fb321792ee87b788193be5a4e3bd326ee4   // SRTP authentication key (output)
SRTP k_s = f1c035c00b5a54a61692c016276c   // SRTP salting key (output)
SRTCP k_e = ab5be0b456235dcf77d5086929bafb38   // SRTCP encryption key (output)
SRTCP k_a = c52fde0b80b0f0bad8d15645cb86e7c7c3d8770e   // SRTCP authentication key (output)
SRTCP k_s = deb5f85f81336a965ed32bb7ede8   // SRTCP salting key (output)
```
Basically, I'm interested ONLY in the key generation/derivation part. I see the following calls in srtp.c and believe that's what I'll need to use to generate the keys mentioned above:

```
srtp_kdf_generate(&kdf, label_rtp_encryption, tmp_key, keyLength);   // SRTP encryption key
srtp_kdf_generate(&kdf, label_rtp_msg_auth, tmp_key, keyLength );   // SRTP authentication key
srtp_kdf_generate(&kdf, label_rtp_salt, tmp_key + (keyLength), rtp_salt_len);  // SRTP salting key
srtp_kdf_generate(&kdf, label_rtcp_encryption, tmp_key, keyLength );  // SRTCP encryption key
srtp_kdf_generate(&kdf, label_rtcp_msg_auth, tmp_key, keyLength );   // SRTCP authentication key
srtp_kdf_generate(&kdf, label_rtcp_salt, tmp_key + keyLength, rtp_salt_len);  // SRTCP salting key
```

The inputs to these calls do not take into account the values of key derivation rate(KDR) and index. I see some code in srtp.c that has "session_keys->mki_id". Is mki_id same as index?
And even if it is, it isn't sent into srtp_kdf_generate() call either directly or part of any other input.
Is there an example that shows how these calls can be used for CAVP testing?

**Comment by pabuhler** [comment] 2019-07-08 21:04
mki stands for MasterKeyIndex, that is not the same as the KDR index you mention.
libsrtp does not support key_derivation_rate, this is an optional feature.

**Comment by amrithathorath** [comment] 2019-07-12 19:17
Thanks for confirming that master key index is in fact MKI.
I'm wondering how would this mki get used in srtp_kdf_generate() call? Because this call does not take session_keys as an argument and mki is part of this session_keys structure.

**Comment by amrithathorath** [comment] 2019-07-26 14:45
When we look at the [RFC](https://tools.ietf.org/html/rfc3711#section-4.3.1) for SRTP, it says the values that are required for generating a key are master key and X. X is key_id XOR'ed with master salt. And this done for all the 6 keys that I've mentioned above. Where is this operation performed within libsrtp? Because when I look at the srtp_kdf_generate() there's no parameter that use salt.

**Comment by paulej** [comment] 2019-07-27 00:18
I think what's happening in the code is this:
* srtp_kdf_init() is called to assign the key and master salt, which calls srtp_cipher_init(), which calls srtp_aes_icm_context_init(). In there, you can see that the salt portion of the salt and key are assigned to c->offset and c->counter writing into the left side 112 bits (so the lower 16 bits are zero).
* srtp_kdf_generate() is called passing in <label>.  It is positioned at 2**16 (per § 4.3.3).  This function calls srtp_cipher_set_iv() which calls srtp_aes_icm_set_iv().  In that function, you'll see c->offset XORed with the IV (i.e., the <label>) and stored in c->counter.

I think that's how `x = key_id XOR master_salt` is accomplished.  I think. I could be wrong.  This definitely isn't the most direct way of doing it.

**Comment by amrithathorath** [comment] 2019-07-27 00:46
Thanks a lot for that update.
But I'm thinking the init function takes in only key isn't it??
Or is the value that's passed into this function a concatenation of key and salt?

**Comment by paulej** [comment] 2019-07-27 02:11
Almost always, the key and salt are concatenated together.  I'd have to go back and look at the code again, but I believe it is here, too.

**Comment by amrithathorath** [comment] 2019-07-27 02:24
@paulej: Thanks a lot, I'll try that out!

**Comment by amrithathorath** [comment] 2019-07-29 13:29
@paulej : Thanks for the comment about concatenating key and salt. That helped me with generation of RTP keys.
But I'm having issues with RTCP keys. Calls are exactly identical to RTP calls as mentioned in one of my comments above (only the lable changes between calls).
What I wanted to confirm was that:
1. I didn't have to initialize kdf context again before generation of RTCP keys
2. The salt length and values will be the same for both RTP and RTCP kets is that correct? In srtp.c I see 2 variables rtp_salt_len and rtcp_salt_len which confused me a bit

**Comment by amrithathorath** [comment] 2019-07-29 13:52
I'm pasting the inputs and expected and actual outputs:

Input:

```
[AES-256]

COUNT = 0
k_master = a263d11aa2dcb2d59b52d6cc77bddb82798179cda98ad2ff70e83d184e9ef4a0
master_salt = 883778c508eb03c45b29e8c0cbfe
kdr = 000000000000
index = a31b4054eff2
index (SRTCP) = 134c512a
```

Expected output : 

```
SRTP k_e = df4bf89f2669868b2ac482f7e25867a0f814437ac29a0e6cfce53dde8306e022
SRTP k_a = 1cd6b9e242c63bee044aa64ad3f8fbde84772218
SRTP k_s = 7fbf73784dc9237bd3f3d3316279
SRTCP k_e = 432f07576604aceb727c0bb9841f55d90373947b3ba947432a44e6baad8490a6
SRTCP k_a = 0b3467e5302099ab3e8eb1444204107318975f88
SRTCP k_s = 6c931c470e15144708855e777219
```
Actual output:

```
srtpKE : df4bf89f2669868b2ac482f7e25867a0f814437ac29a0e6cfce53dde8306e022  //matches
srtpKA : 1cd6b9e242c63bee044aa64ad3f8fbde84772218  //matches
srtpKS : 7fbf73784dc9237bd3f3d3316279  //matches
srtcpKE : 61a74e317fd7580bfa7cbc7d6f2ea0830e29c7db157de5abdc2967a0cba197e0  // don't match expected output
srtcpKA :fd051ca4df2c002b1a5f68d2a162dfdf01dd65a6  // don't match expected output
srtcpKS : 922096357d7b767e9294e84d2f24  // don't match expected output

```

**Comment by amrithathorath** [comment] 2019-08-02 15:15
Any pointers to solve this issue are appreciated!

**Comment by paulej** [comment] 2019-08-02 16:43
You're getting unexpected results calling srtp_stream_init_keys()?  You have the cipher for both RTP and RTCP set properly?

I've not had time to look into this and won't for a week or so due to travel and deadlines.

**Comment by amrithathorath** [comment] 2019-08-02 17:10
No unexpected results are for SRTCP keys. SRTP keys are generated as expected.

Correct SRTP keys
```
srtp_kdf_generate(&kdf, label_rtp_encryption, tmp_key, keyLength);   // SRTP encryption key
srtp_kdf_generate(&kdf, label_rtp_msg_auth, tmp_key, keyLength );   // SRTP authentication key
srtp_kdf_generate(&kdf, label_rtp_salt, tmp_key + (keyLength), rtp_salt_len);  // SRTP salting key
``` 
Incorrect SRTCP keys
```
srtp_kdf_generate(&kdf, label_rtcp_encryption, tmp_key, keyLength );  // SRTCP encryption key
srtp_kdf_generate(&kdf, label_rtcp_msg_auth, tmp_key, keyLength );   // SRTCP authentication key
srtp_kdf_generate(&kdf, label_rtcp_salt, tmp_key + keyLength, rtp_salt_len);  // SRTCP salting key
```
The calls are very much similar except for labels.
The cipher that's set for SRTP keys will be used for SRTCP as well.

**Comment by paulej** [comment] 2019-08-02 17:29
My question is if you are getting unexpected results calling srtp_stream_init_keys().  That generates keys for a stream for both RTP and RTCP.  Those will start with 0 index values and if you're seeing issues, maybe the issue lies with how the index is being set?  I'm not suggesting there is no bug. but just curious if you see that issue even with 0 index values.

**Comment by amrithathorath** [comment] 2019-08-02 17:35
I do not call srtp_stream_init_keys().
I only call srtp_kdf_init(), srtp_kdf_generate() and srtp_kdf_clear().
And none of these calls take in index as their arg, so I believe I'm already running it with 0 index value.

**Comment by pabuhler** [comment] 2019-08-05 04:44
@amrithathorath  where are you getting the expected values from? Have they taken in to account https://www.rfc-editor.org/errata/eid3712 ?

**Comment by amrithathorath** [comment] 2019-08-05 13:33
The expected results are from a response file that was generated using OpenSSL library and results were validated by the lab. And SRTP generates same value even with multiple runs, I'm using that for reference. The library used to generate this expected response file was different, but results should still match.

**Comment by lisarabe** [comment] 2019-08-23 16:47
I'm working on this also (doing CAVP testing for SRTP) and am following this with interest.  Amrithathorath, have you figured out what went wrong with some of your responses?

**Comment by pabuhler** [comment] 2019-08-27 15:04
Once again have you confirmed the openssl output takes in to account https://www.rfc-editor.org/errata/eid3712   ?  Can try to patch libsrtp to have the position of the label and see what the results are. If I get some time tomorrow I will try to see if that makes a difference based on the expected results you posted.

**Comment by amrithathorath** [comment] 2019-08-29 18:36
@lisarabe , @pabuhler : Just checking in to see if any of you guys could confirm or deny that my values are wrong.

**Comment by lisarabe** [comment] 2019-09-05 15:12
@amrithathorath I am getting the same results as you.  Have you made any progress since the last time you posted?

**Comment by pabuhler** [comment] 2019-09-06 08:32
Hi, with the following patch to libsrtp I get both RTP & RTCP keys to match what you posted as expected output given the key and salt you provided.
```
--- a/srtp/srtp.c
+++ b/srtp/srtp.c
@@ -718,7 +718,11 @@ static srtp_err_status_t srtp_kdf_generate(srtp_kdf_t *kdf,
 
     /* set eigth octet of nonce to <label>, set the rest of it to zero */
     v128_set_to_zero(&nonce);
-    nonce.v8[7] = label;
+    if (label == label_rtcp_encryption || label == label_rtcp_msg_auth || label == label_rtcp_salt) {
+        nonce.v8[9] = label;
+    } else {
+        nonce.v8[7] = label;
+    }
```
This is related to the RFC Errata for SRTP (RFC 3711) that I previously mentioned https://www.rfc-editor.org/errata/eid3712.  To try and explain it simply libsrtp places the the label at a fixed position in the nonce where as the code that generated your expected output positions the label based on the size of the index, 48 bits for RTP and 32 bits for RTCP. The errata states that the SRTCP index should also be treated as a 48 bit value which will result in the label being at the same position for both RTP and RTCP. SRTP implementations should follow this errata to be interoperable.
I hope this clears things up for you?

**Comment by amrithathorath** [comment] 2019-09-06 13:38
@pabuhler : Thanks a lot for that explanation.
I'm looking the validation system for [SRTP ](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/components/askdfvs.pdf) (page 15 of doc) on the NIST website and this is what we follow to obtain our FIPS validation. 
Here it says 48-bits index for SRTP and 32-bits for SRTCP.
This doc is more recent when compared to Errata.

**Comment by amrithathorath** [comment] 2019-09-06 20:38
@pabuhler : I've applied the changes you tried.
I see the expected responses for AES-128 and AES-256. However AES-192 seems to return answers that don't match expected output.

```
// kdf_keylen = keylength + salt_len
// AES-128    = 16        +    14     = 30
// AES-192    = 24        +    14     = 38
// AES-256    = 32        +    14     = 46

```
In srtp.c, I see kdf_keylen is initialized to 30 and gets assigned to 46 only if (rtp_keylen > kdf_keylen).
That explains why it works for AES-128 and AES-256. But I don't see anything for AES-192 (kdf_keylen should be 38 for AES-192). 
Does it mean the library does not support AES-192?

**Comment by pabuhler** [comment] 2019-09-09 08:07
@amrithathorath  AES-192 is not supported natively by libsrtp, it is only supported when libsrtp is used with openssl or nss (--enable-openssl) . This is I think because the AES-192 support was only added in the last few years and the contributor only included support for openssl as that is the way libsrtp is predominantly used and AES-192 is not a common cipher (but I could be wrong). When I use --enable-openssl then I successfully get the NIST expected values, can you confirm? It should be noted that it is mostly the same kdf code being used when configured with open ssl, it will just use the AES cipher provided by openssl instead of the native one.

We need to find out how to proceed with the different expectations in the NIST document compared to RFC 3711 + errata. It looks like the original NIST document was created before the errata was reported. I will try to follow this up.

**Comment by amrithathorath** [comment] 2019-09-09 12:52
@pabuhler : Thanks for confirming about AES-192. I'll try to run with "enable-openssl" and report back what I see.
And please keep me posted on the NIST and RFC+errata issue.

**Closed** 2020-01-16 16:26 UTC

**Comment by sirzooro** [comment] 2024-07-10 10:18
@ARao0123 do you know if AES-192 was fixed or not? Recently I was trying to add AES-192 support to [pion srtp](https://github.com/pion/srtp) and found that it generates different output than libsrtp2. It uses the same code is used the for AES-128 and AES-256, so I suspect that libsrtp2 has broken implementation of AES-192.

**Comment by ARao0123** [comment] 2024-07-11 13:20
@sirzooro : sorry I'm not following this issue anymore.
