### ISSUE TITLE
srtp_create fail for first few packets in armv7

### ISSUE THREAD

**Issue by robelsharma** [cisco/libsrtp#305] opened 2017-05-15 16:06 UTC
Hi Team,
I have been seeing this issue consistently in raspberry pi3 armv7. When I debugged the source code it looks like cypher types are not initialized. Meaning the following function return some invalid or big integer for cypher type in place of 1, 2 or 3.

crypto_kernel.c +491 (v1.5.x)
`srtp_crypto_kernel_get_cipher_type()`

I have tried 1.4.5 the old release of srtp in raspberry pi3 and still seeing this issue. As the title says it gets better after 5 or 10 packets encrypt/decrypt failure.  Am I missing something or do I need to add something in the build configuration? Please advise.

Thanks,
Robel Sharma

**Comment by paulej** [comment] 2017-05-15 18:10
Is it the sender that it sending wrong data?  The ciphers are not going to auto-configure later.  They would have been configured upon initialization, so it doesn't make any sense that it would suddenly start working after 10 packets or so.

There was an issue (#304) discovered for big endian processors.  As I understand, the ARM can operate in either mode and, obviously, if the endianness isn't right, the behavior can be quite unpredictable.  Might be be related to that?

**Comment by robelsharma** [comment] 2017-05-15 18:52
It reproduces for both (send and receive) in raspberry pi.  It's been initialized at the beginning and I found that the same code base works on the android phone. Looks like my pi is little endian.

**Comment by paulej** [comment] 2017-05-15 19:03
If you do a "run maketest", do all the tests pass?  I'm baffled as to why the first few packets would fail to decrypt (or encrypt) properly.

**Comment by robelsharma** [comment] 2017-05-15 19:38
Have cloned the branch `1_5_x_throttle` as I am using 1.5.x and here is the output for `run maketest`,
> gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include -fPIC  -fPIC -Wall -O4 -fexpensive-optimizations -funroll-loops -L.  -o test/dtls_srtp_driver test/dtls_srtp_driver.c test/getopt_s.c libsrtp.a  -lsrtp
> Build done. Please run 'make runtest' to run self tests.
> running libsrtp test applications...
> crypto/test/cipher_driver -v >/dev/null
> crypto/test/kernel_driver -v >/dev/null
> test/rdbx_driver -v >/dev/null
> test/srtp_driver -v >/dev/null
> test/roc_driver -v >/dev/null
> test/replay_driver -v >/dev/null
> test/dtls_srtp_driver >/dev/null
> crypto/test/rand_gen_soak -v >/dev/null
> cd test; /home/root/srtp/libsrtp/test/rtpw_test.sh >/dev/null	
> ./rtpw: couldn't open file /usr/share/dict/words
> make: *** [Makefile:35: runtest] Error 255
>

**Comment by paulej** [comment] 2017-05-15 19:48
The error is due to the missing dictionary file.  We're changing that in the upcoming 2.1 release, but for now is it possible to either install the "words" or "spell" package (not sure which one will contain that file /usr/share/dict/words on your system, just create a file with that name with some random words out of a dictionary, or modify the source to point to a different file for the same purpose?  (It's a #define in the test code somewhere).  (I suspect all tests will pass, because the tests made it this far...)

**Comment by pabuhler** [comment] 2017-07-04 12:29
@robelsharma  Is this still an issues for you? As of release 2.1.0 there is no longer a dependency on /usr/share/dict/words so performing a `make runtest` should work.

There is a 1.6.x throttle branch that will be used to create a new 1.X release, if you use that branch does the problem still exists?

**Comment by pabuhler** [comment] 2017-10-26 12:15
@robelsharma I will close this issues now as there has been no progress for a while. If this is still a problem then please reopen. I would suggest moving to libsrtp 2.1 if possible.

**Closed by pabuhler** 2017-10-26 12:15 UTC

**Comment by tarask1nRing** [comment] 2019-02-14 16:55
I can confirm that bug on raspberry pi. The root cause is that the memory for policy structure is not zeroed on initialize. So, it has random data in "enc_xtn_hdr", "enc_xtn_hdr_count" fields which leads to error in "srtp_crypto_alloc" method.

./test/rtp_decoder -t 0 -e 128 -k a928ea6dcb646c9700ef2e38d832169302f15cd48e4efb2154714887023d <~/test.pcap

**Comment by anyconnectiot** [comment] 2019-02-15 03:23
Sorry, pabuhler. I went with those few packet failure. Looks like now it is fixed on the new version. I will do a dry run sometime later.

**Comment by robelsharma** [comment] 2019-02-15 03:25
Sorry, pabuhler. I went with those few packet failure. Looks like now it is fixed on the new version. I will do a dry run sometime later.
