### ISSUE TITLE
configure.in:11: error: possibly undefined macro: AM_PROG_AR libsrtp 1.5.4  centos 6.9 

### ISSUE THREAD

**Issue by mariarti** [cisco/libsrtp#297] opened 2017-04-28 12:06 UTC
```
libsrtp-1.5.4]# autoconf
configure.in:11: error: possibly undefined macro: AM_PROG_AR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

```
```
libsrtp    
v1.5.4
078c4a5
```

```
# automake --version
automake (GNU automake) 1.11.1
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

**Comment by itollefsen** [comment] 2017-05-02 09:55
While it's reported against a different version of libsrtp, this is still a duplicate of #296.

**Closed** 2017-05-02 11:59 UTC
