### ISSUE TITLE
applications wanting to use srtp_hdr_t and other things from private headers

### ISSUE THREAD

**Issue by dpocock** [cisco/libsrtp#532] opened 2021-04-09 17:49 UTC
There are at least two applications who want to use bits of srtp_priv.h and friends.

reSIProcate tries to use srtp_hdr_t in one of the unit tests, it works with an embedded copy of libsrtp but it doesn't work when using libsrtp2-dev packages because the package maintainers refuse to distribute private headers.

Trying to build qtwebengine on Debian
https://bugs.debian.org/866784

Trying to build unit tests for reSIProcate reflow/dtls_wrapper/test
https://www.resiprocate.org/bugzilla/show_bug.cgi?id=169

**Comment by paulej** [comment] 2021-04-10 00:21
srtp_hdr_t is a structure that represents an RTP header.  It's not specific to SRTP, really.  Why not just reproduce that if it's for testing purposes only?  There is no risk of the RTP header changing in libsrtp since it's defined in RFC 3550, not RFC 3711.  Are the other dependencies like that?

**Comment by pabuhler** [comment] 2021-04-11 18:05
@dpocock I tried to follow the links but now where was there an explanation as to why these projects need srtp_hdr_t. Like Paul mentioned this just a generic RTP header structure and is not part of the libSRTP api. My suggestion would be for these projects to remove / change there use of this structure or come with a very compelling argument as to why libSRTP should maintain a public version of this structure just for the use of a few other projects.

**Comment by JeremySigler** [comment] 2021-08-28 17:33
Merging would not work in this instance.too much damage.

**Comment by pabuhler** [comment] 2022-12-15 04:12
I am going to close this as it should not be used outside of library code.

**Closed by pabuhler** 2022-12-15 04:12 UTC
